### PR TITLE
dialog box to ask hda install code during anaconda install enabled

### PR DESCRIPTION
**Pull request by advir29**
Install code is asked and verified for validity. If the verification is successful, it's stored in /var/hda/install-code.txt.

The iso generated for Amahi Express Install Disk 11 after incorporating these changes can be downloaded from:
https://drive.google.com/open?id=1wXoZr7T3zMJRz4pBw1xm8aOyfse1vhM7

### CODE REVIEW

**Review by sanjitchak — COMMENTED** [review]
@advir29  I am sorry for not realizing that you were contributing too. I would have readily updated the GitHub repo then. Wanted to sort few things out before updating the repo, which includes automatic setup of amahi server.

But anyways,
@advir29  found a way to verify the INSTALL CODE,  which seems to be working well. So, awesome work there.  
He has added this verification after the installation finishes, which brings us to 2 scenarios:-

Screenshots are given in comment section.

1st Scenario (@advir29 ):-
Advantage - 
1. INSTALL CODE gets verified first before installation finishes.
2. Anaconda Module may not be required at all, for now at least. Only one kickstart file is enough for installation.
 
Disadvantage - 
1. The user has to wait for the whole installation to finish before the user can input their INSTALL CODE. 
2. Verification of INSTALL CODE takes few seconds before 'Invalid code' dialog box pops up. In that case, the user might think that INSTALL CODE is correct and the user may run off to do something else.

2nd Scenario (mine):-
Advantage - 
1. The installation will not begin if INSTALL CODE is not entered. After that, everything is automatic, including automatic setup of amahi server.

Disadvantage -
1. Extra anaconda addon is required.
2. Still has to find a way to verify INSTALL CODE. Although @advir29 may apply his logic of verifying INSTALL CODE in anaconda addon before installation begins. This will ensure that installation will not begin if wrong INSTALL CODE is entered.

**Comment by sanjitchak** [comment]
@advir29  Scenario :- 
rsz_virtualbox_fedora_amahi_server_21_04_2018_14_18_02

My Scenario :-
rsz_virtualbox_fedora_amahi_server_21_04_2018_13_52_32

**Comment by advir29** [comment]
I compiled your work but I didn't get an option to enter amahi server setup. Could you verify that part.

**Comment by sanjitchak** [comment]
@advir29  hope it will compile correctly now.

**Comment by advir29** [comment]
You could now apply the logic present in ks.cfg %post section. [https://github.com/advir29/anaconda-addon/blob/master/ks.cfg](url)
Verify the install code using that logic and echo the install code to intall-code.txt.  
add the hda-install "install-code.txt" command to hda-install-script.sh.
Compile iso.]
Your install disk is ready for final use. 😃 

For any help feel free to ask.

**Comment by sanjitchak** [comment]
Thanks @advir29 . That made our work of verification quite easy.
Yes, sure. We will ask.  :smile:

**Pull request closed without merging**
